sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
      - v.2
notifications:
  email: false
node_js:
  - 6.1
  - 6
  - 5.6.0
  - 4.3.0
before_install:
  - npm i -g npm@^3.8.2
before_script:
  - npm prune
script:
  - npm run test